### ISSUE TITLE
JOSS review: functionality documentation & testing

### ISSUE THREAD

**Issue by astrom-tom** [0xCoto/Virgo#12]
Hi @0xCoto 

**Functionality documentation:**

The _in-code_ documentation is an important problem.
There is no documentation of the functions that are coded in the package.
For example, let's take the function given in the example usage:

```
>>>import virgo
>>>help(virgo.predict) 
Help on function predict in module virgo.virgo: 
predict(lat, lon, height=0, source='', date='', plot_sun=True, plot_file='')`

>>>help(virgo.observe)
Help on function observe in module virgo.virgo:
observe(obs_parameters, spectrometer='wola', obs_file='observation.dat', start_in=0)
```

--> There is no documentation of what it does, the input format and the output that is given. Please document every function of the package. 

**Testing:**
In addition, I did not see any automated test mention in the readme. You must be able to test your code. It might be an automatic test suite (with unittest or pytest package for example) or at least a  manual procedure that tell us how to test your code.

**Comment by 0xCoto** [comment]
In-code documentation has been implemented for every function.

For example,
```python
>>> import virgo
>>> help(virgo.predict)
```
now clarifies the role of the function and the properties of each parameter:
```
predict(lat, lon, height=0, source='', date='', plot_sun=True, plot_file='')
    Plots source Alt/Az given the observer's Earth coordinates.
    
    Args:
            lat: float. Observer latitude [deg]
            lon: float. Obesrver longitude [deg]
            height: float. Observer elevation [m]
            source: string. Source name
            date: string. Date in YYYY-MM-DD format. If no date is given, it defaults to today's system date.
            plot_sun: bool. Also plot Sun position for reference
            plot_file: string. Output plot filename
```
---
Since it is unlikely that a reviewer would have access to appropriate hardware, we have included an example observation file obtained with Virgo on the [repository](https://github.com/0xCoto/Virgo/tree/master/joss_example) for software testing and verification purposes, as described [here](https://virgo.readthedocs.io/en/latest/examples.html#offline-experiments). Please let me know if this is sufficient, or if you were envisioning something else.
